apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: collectd-node-agent
  namespace: kube-system
  labels:
    app: collectd-node-agent
spec:
  template:
    metadata:
      labels:
        name: collectd-node-agent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: kubevirt-privileged
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubevirt.io/schedulable: "true"
      containers:
      - name: collectd
        ports:
        - containerPort: 9090
          protocol: TCP
        image: fromanirh/collectd:0.2.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: collectd-config
          mountPath: /etc/collectd
        - name: proc
          mountPath: /mnt/proc
          readOnly: true
        - name: root
          mountPath: /hostfs
          readOnly: true
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
      volumes:
      - name: collectd-config
        configMap:
          name: collectd-config
          items:
          - key: node-collectd.conf
            path: collectd.conf
      - name: proc
        hostPath:
          path: /proc
      - name: root
        hostPath:
          path: /

