kind: ConfigMap
apiVersion: v1
metadata:
  name: collectd-config
  namespace: kube-system
data:
  node-collectd.conf: |-
    LoadPlugin syslog
    <Plugin syslog>
       LogLevel info
    </Plugin>
    LoadPlugin exec
    <Plugin exec>
       Exec "/usr/local/libexec/procwatch" "/etc/procwatch.json"
    </Plugin>
    LoadPlugin write_prometheus
    <Plugin "write_prometheus">
      Port "9090"
    </Plugin>

