apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubevirt-vmi
  namespace: kube-system
  labels:
    openshift.io/cluster-monitoring: ""
    prometheus.kubevirt.io: ""
spec:
  selector:
    matchLabels:
      vmi.prometheus.kubevirt.io: ""
  endpoints:
  - port: metrics-vmi
    scheme: http
